### ISSUE TITLE
[ASK] Enable for 9300H?

### ISSUE THREAD

**Issue by aryayudha** [rinmichi/Nitro-5-AN515-54-Hackintosh#1]
Hi, it's your efi enable to 9300H type? thanks

**Comment by rinmichi** [comment]
Hi @aryayudha, i didn't tried that yet. But the thing i know about opencore with my config it compatible around 9th gen intel CPU, you may just need to generate new CPU Friend Data Freq. You can generate with this tool https://github.com/corpnewt/CPUFriendFriend
