### ISSUE TITLE
Informations

### ISSUE THREAD

**Issue by avelinocneto** [rinmichi/Nitro-5-AN515-54-Hackintosh#2]
1- Any news about the original wifi chip ?
2- How do I install it?

**Comment by restuindrawan** [comment]
Hi @avelinocneto, Sorry i'm late to replying
Intel AX200 still work in progress by [OpenIntelWireless](https://github.com/OpenIntelWireless) Community
The way you install it just compile it by your own, because they doesn't make the release yet

**Comment by restuindrawan** [comment]
Update @avelinocneto
They already release the alpha version, now you can try it
Do keep in mind, it not work as Native supported WiFi Card
It work's like a usb dongle now, better than nothing and don't expect AirDrop, SideCar, Handoff working
Open their site for more info https://OpenIntelWireless.github.io

**Comment by avelinocneto** [comment]
Hi @rinmichi !
Thanks for informations.
Do you have a quick installation guide? 
I've made an Hackintosh in past, but a time ago, using Clover in another notebook.
I will use dual boot with Windows thats already installed and I can't format it by now.

**Comment by restuindrawan** [comment]
Sorry @avelinocneto, I'm not very good at explaining the installation guide.
So I just gave a reference to The Dortania community https://dortania.github.io/OpenCore-Install-Guide/
I learn from dotania, their guide are detailed about every component to build a hack
