### ISSUE TITLE
Can't work on my Acer Nitro 5 AN515-54

### ISSUE THREAD

**Issue by victortassinari** [rinmichi/Nitro-5-AN515-54-Hackintosh#3]
I generate the usb bootable disk with gibmac script with the lasted version of mac os catalina.

The version that i tested is 10.15.6 

I replace the efi files with files of this repository. The boot is successful, but I can't install system, the error is An internet connection is required to install macos
![1599983042184789573632683241751](https://user-images.githubusercontent.com/6419541/93013112-c732d000-f57b-11ea-95e6-a17234a2ffc8.jpg)

**Comment by restuindrawan** [comment]
Hi @victortassinari, thanks for testing my efi files. Make sure you create the full install from the gib script not recovery only, just use the script to download the latest version of mac, then use the original create bootable with apple original command (if you has access to the mac os)

**Comment by restuindrawan** [comment]
Or if you only has access to windows due to gib script limitation in windows that only makes recovery only image, you could try the olarila image and create the bootable usb with balena etcher after that you could mount the efi partition of the usb drive to replace olarila efi with this repo

**Comment by caophuoclong** [comment]
hello, i have the same your device, i have ssd micron 2200 and ssd kingston, i don't know how to disable ssd micron 2200. I read your readme at disable micron 2200 but i can't find boot arguments. Can you help me

**Comment by restuindrawan** [comment]
> hello, i have the same your device, i have ssd micron 2200 and ssd kingston, i don't know how to disable ssd micron 2200. I read your readme at disable micron 2200 but i can't find boot arguments. Can you help me

Sorry for late reply, you could use nvme=-1 argument but, it will disable all nvme device
you could try the dortania disabling pci device
